### ISSUE TITLE
Nom de repo disruptif

### ISSUE THREAD

**Issue by SirWrexes** [theocerutti/-PATHFINDING-Generator-Dante-Maze#1]
Il y a une place spéciale réservée en enfer pour les personnes qui ont l'idée de mettre un '-' en premier caractère d'un nom de dossier.

Moi qui voulait seulement trouver un générateur pour faire des labyrinthes histoire de débugger mon solveur, je me retrouve coincé avec un dossier que je ne peux pas supprimer. 
![image](https://user-images.githubusercontent.com/5567164/77275825-87201e00-6cb9-11ea-8157-6f6a6e302e24.png)

Je me retrouve obligé d'installer un explorateur graphique (beurk) pour le renommer. 😅

**Comment by theocerutti** [comment]
Je ne savais pas qu'un simple tiret pouvait engendrer de tel problèmes !
C'est corrigé ! Merci
